---
name: Label Checker
on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - edited

jobs:

  check_semver_label:
    name: Check semantic version label
    runs-on: ubuntu-latest
    steps:
      - uses: agilepathway/label-checker@use-go
        with:
          labels: >
            [
              "major",
              "minor",
              "patch"
            ]
