---
name: Label Checker
on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:

  check_semver_label:
    name: Check semantic version label
    runs-on: ubuntu-latest
    steps:
      - uses: skeeping/label-checker@patch-1
        with:
          one_of: major,minor,patch
          repo_token: ${{ secrets.GITHUB_TOKEN }}
